---
# tasks file for install-docker-ubuntu
- name: Remove old docker packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    purge: yes
    state: absent
  become: yes

- name: Remove docker folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/docker
    - /var/lib/containerd
    - /etc/docker
    - /etc/containerd
  become: yes

- name: Install packages required by docker
  apt:
    name:
      - ca-certificates
      - curl
      - lsb-release
    state: latest
    update_cache: yes
  become: yes

- name: Add an Apt signing key for docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  retries: 2
  delay: 3
  register: result
  until: result["failed"] == false
  become: yes

- name: Add docker to apt repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable
    state: present
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: yes

- name: Install docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  become: yes

- name: Create /etc/docker
  file:
    path: /etc/docker
    state: directory
  become: yes

- name: Copy docker daemon config
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: "0640"
  become: yes

- name: Enable docker service, reload and restart
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: yes
