---
# tasks file for install-docker-ubuntu
- name: Remove old docker packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    purge: yes
    state: absent
  become: yes

- name: Remove docker folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/docker
    - /var/lib/containerd
    - /etc/docker
    - /etc/containerd
  become: yes

- name: Ensure that the containerd configuration directory is present
  become: true
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Ensure that containerd configuration is up-to-date
  become: true
  template:
    src: config.j2.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0600"
  notify: Restart containerd service

- name: Install packages required by docker
  apt:
    name:
      - ca-certificates
      - curl
      - lsb-release
    state: latest
    update_cache: yes
  become: yes

- name: Add an Apt signing key for docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  retries: 2
  delay: 3
  register: result
  until: result["failed"] == false
  become: yes

- name: Add docker to apt repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable
    state: present
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

- name: Ensure that the official docker-ce repository is present
  become: true
  apt_repository:
    repo: |
      deb [arch=amd64] https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable
  register: _repo

- name: Ensure that docker-ce package is pinned to a specified version
  become: true
  copy:
    content: |
      Package: containerd.io
      Pin: version {{ cf_containerd_version }}
      Pin-Priority: 1000
    dest: /etc/apt/preferences.d/containerd.pref
    owner: root
    group: root
    mode: "0644"

- name: Ensure that containerd.io package is installed
  become: true
  apt:
    update_cache: "{{ _repo is changed }}"
    name:
      - "containerd.io={{ containerd_version }}"
      - apparmor
    state: present
